app:
  env:
    server.port: "{{ app_port }}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://dbserver:5432/appdb

service:
  workingdir: "{{ ansible_user_dir }}/backend"
  execstart: "java -jar target/agri-coop-0.0.1-SNAPSHOT.jar"
