---
- hosts: all
  become: true
  tasks:
    - name: Check if Docker is installed
      shell: docker --version && docker compose version
      register: docker_version_result
      ignore_errors: true

    - name: Set Docker installed fact
      set_fact:
        docker_installed: "{{ docker_version_result.rc == 0 }}"

    - name: Include docker tasks if Docker is not installed
      include_tasks: ../tasks/docker-tasks.yaml
      when: not docker_installed
