---
- hosts: all

  pre_tasks:
    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes
      become: true

  tasks:
    - name: "debug backend_dir"
      ansible.builtin.debug:
        msg: "backend_dir {{ ansible_user_dir }}"

    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/andreasrous/agri-coop.git"
        dest: "{{ project_root }}"
        version: "{{ branch }}"
        force: yes

    - name: "Populate application.properties"
      lineinfile:
        dest: "{{ backend_dir }}/src/main/resources/application.properties"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items:
        - "{{ app.env | dict2items }}"

    - name: "Build the Spring application"
      command: "./mvnw package -Dmaven.test.skip "
      args:
        chdir: "{{ backend_dir }}"

    #      - name: "Run the Spring application"
    #        command: "java -jar target/agri-coop-0.0.1-SNAPSHOT.jar"
    #        args:
    #            chdir: "{{ backend_dir }}"

    - name: copy spring service file
      template:
        src: ../files/spring.service.j2
        dest: "/etc/systemd/system/spring.service"
      become: true
      become_user: root
      notify: restart spring

    - name: reload spring service
      service:
        name: spring
        state: restarted
      become: true

    - name: ensure spring service started
      service:
        name: spring
        state: started
        enabled: yes
      become: true

    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes
      become: true

    - name: copy nginx conf file
      template:
        src: ../files/nginx.http.j2
        dest: "/etc/nginx/sites-available/spring"
      become: true

    - name: enable spring site in nginx
      file:
        src: "/etc/nginx/sites-available/spring"
        dest: "/etc/nginx/sites-enabled/spring"
        state: link
      become: true
      notify: restart nginx

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: true
      notify: restart nginx

  handlers:
    - name: restart spring
      service:
        name: spring
        state: restarted
      become: true

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: true
