---
- hosts: appservers

  pre_tasks:
    - name: Find my public ip
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: See public ip
      debug:
        var: ip_response.content

    - name: Install Nginx
      package:
        name: nginx
        state: latest
      become: true

    - name: Install nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: "debug"
      ansible.builtin.debug:
        msg: "PATH : {{ ansible_env.PATH }}"

    - name: Install node
      shell: |
        source $HOME/.nvm/nvm.sh && nvm install 20.12.1
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v20.12.1"

    - name: Install Git
      package:
        name: git
        state: latest
      become: true

  tasks:
    - name: "Clone the Vue repository"
      git:
        repo: "https://github.com/andreasrous/devops-frontend.git"
        dest: "{{ frontend_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: copy env file
      shell: "cp {{ frontend_dir }}/.env.example {{ frontend_dir }}/.env"

    - name: populate  ~/.env
      lineinfile:
        dest: "{{ frontend_dir }}/.env"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}='{{item.value}}'"
      with_items:
        - "{{app | dict2items}}"

    - name: "Install dependencies"
      shell: |
        export PATH=$PATH:~/.nvm/versions/node/v20.12.1/bin; npm install
      args:
        chdir: "{{ frontend_dir }}"

    - name: "Build the Vue.js application"
      shell: |
        export PATH=$PATH:~/.nvm/versions/node/v20.12.1/bin; npm run build
      args:
        chdir: "{{ frontend_dir }}"

    - name: Copy dist in nginx location
      copy:
        src: "{{ frontend_dir }}/dist/"
        dest: "{{ site_location }}"
        remote_src: True
        mode: 7777
        force: true
      notify: restart nginx
      become: true

    - name: copy nginx conf file
      template:
        src: ../files/nginx.vue.j2
        dest: "/etc/nginx/sites-available/vue"
      become: true

    - name: enable vue site in nginx
      file:
        src: "/etc/nginx/sites-available/vue"
        dest: "/etc/nginx/sites-enabled/vue"
        state: link
      become: true

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: true
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: true
